/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.21
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ecpayBase

import (
	"encoding/json"
)

// TradeInfo struct for TradeInfo
type TradeInfo struct {
	// **特店編號(由綠界提供)**
	MerchantID string `json:"MerchantID"`
	// **特店交易編號(由特店提供)** 訂單產生時傳送給綠界的特店交易編號。
	MerchantTradeNo string `json:"MerchantTradeNo"`
	// **特店旗下店舖代號** 提供特店填入分店代號使用，僅可用英數字大小寫混合。
	StoreID string `json:"StoreID"`
	// **綠界的交易編號** 首次授權所產生的綠界交易編號
	TradeNo string `json:"TradeNo"`
	// **交易金額**
	TradeAmt int `json:"TradeAmt"`
	// **付款時間** 格式為 yyyy/MM/dd HH:mm:ss
	PaymentDate ECPayDateTime         `json:"PaymentDate"`
	PaymentType ReturnPaymentTypeEnum `json:"PaymentType"`
	// **手續費合計**  履約結束後才會計算，未計算前為 0
	HandlingCharge int `json:"HandlingCharge"`
	// **通路費**
	PaymentTypeChargeFee float32 `json:"PaymentTypeChargeFee"`
	// **訂單成立時間** 格式為 yyyy/MM/dd HH:mm:ss
	TradeDate ECPayDateTime `json:"TradeDate"`
	// **交易狀態**    回傳值：   若為 0 時，代表交易訂單成立未付款   若為 1 時，代表交易訂單成立已付款   若為 10200095 時，代表消費者未選擇付款方式，故交易失敗。
	TradeStatus string `json:"TradeStatus"`
	// **商品名稱**
	ItemName string `json:"ItemName"`
	// **自訂名稱欄位1**   提供合作廠商使用記錄用客製化使用欄位
	CustomField1 string `json:"CustomField1"`
	// **自訂名稱欄位2**   提供合作廠商使用記錄用客製化使用欄位
	CustomField2 string `json:"CustomField2"`
	// **自訂名稱欄位3**   提供合作廠商使用記錄用客製化使用欄位
	CustomField3 string `json:"CustomField3"`
	// **自訂名稱欄位4**   提供合作廠商使用記錄用客製化使用欄位
	CustomField4 string `json:"CustomField4"`
	// **檢查碼** 特店必須檢查檢查碼`CheckMacValue`來驗證，請參考附錄檢查碼機制。
	CheckMacValue string `json:"CheckMacValue"`
}

// NewTradeInfo instantiates a new TradeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTradeInfo(merchantID string, merchantTradeNo string, storeID string, tradeNo string, tradeAmt int, paymentDate ECPayDateTime, paymentType ReturnPaymentTypeEnum, handlingCharge int, paymentTypeChargeFee float32, tradeDate ECPayDateTime, tradeStatus string, itemName string, customField1 string, customField2 string, customField3 string, customField4 string, checkMacValue string) *TradeInfo {
	this := TradeInfo{}
	this.MerchantID = merchantID
	this.MerchantTradeNo = merchantTradeNo
	this.StoreID = storeID
	this.TradeNo = tradeNo
	this.TradeAmt = tradeAmt
	this.PaymentDate = paymentDate
	this.PaymentType = paymentType
	this.HandlingCharge = handlingCharge
	this.PaymentTypeChargeFee = paymentTypeChargeFee
	this.TradeDate = tradeDate
	this.TradeStatus = tradeStatus
	this.ItemName = itemName
	this.CustomField1 = customField1
	this.CustomField2 = customField2
	this.CustomField3 = customField3
	this.CustomField4 = customField4
	this.CheckMacValue = checkMacValue
	return &this
}

// NewTradeInfoWithDefaults instantiates a new TradeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTradeInfoWithDefaults() *TradeInfo {
	this := TradeInfo{}
	return &this
}

// GetMerchantID returns the MerchantID field value
func (o *TradeInfo) GetMerchantID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantID
}

// GetMerchantIDOk returns a tuple with the MerchantID field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetMerchantIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantID, true
}

// SetMerchantID sets field value
func (o *TradeInfo) SetMerchantID(v string) {
	o.MerchantID = v
}

// GetMerchantTradeNo returns the MerchantTradeNo field value
func (o *TradeInfo) GetMerchantTradeNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantTradeNo
}

// GetMerchantTradeNoOk returns a tuple with the MerchantTradeNo field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetMerchantTradeNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantTradeNo, true
}

// SetMerchantTradeNo sets field value
func (o *TradeInfo) SetMerchantTradeNo(v string) {
	o.MerchantTradeNo = v
}

// GetStoreID returns the StoreID field value
func (o *TradeInfo) GetStoreID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StoreID
}

// GetStoreIDOk returns a tuple with the StoreID field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetStoreIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreID, true
}

// SetStoreID sets field value
func (o *TradeInfo) SetStoreID(v string) {
	o.StoreID = v
}

// GetTradeNo returns the TradeNo field value
func (o *TradeInfo) GetTradeNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetTradeNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeNo, true
}

// SetTradeNo sets field value
func (o *TradeInfo) SetTradeNo(v string) {
	o.TradeNo = v
}

// GetTradeAmt returns the TradeAmt field value
func (o *TradeInfo) GetTradeAmt() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.TradeAmt
}

// GetTradeAmtOk returns a tuple with the TradeAmt field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetTradeAmtOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeAmt, true
}

// SetTradeAmt sets field value
func (o *TradeInfo) SetTradeAmt(v int) {
	o.TradeAmt = v
}

// GetPaymentDate returns the PaymentDate field value
func (o *TradeInfo) GetPaymentDate() ECPayDateTime {
	if o == nil {
		var ret ECPayDateTime
		return ret
	}

	return o.PaymentDate
}

// GetPaymentDateOk returns a tuple with the PaymentDate field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetPaymentDateOk() (*ECPayDateTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentDate, true
}

// SetPaymentDate sets field value
func (o *TradeInfo) SetPaymentDate(v ECPayDateTime) {
	o.PaymentDate = v
}

// GetPaymentType returns the PaymentType field value
func (o *TradeInfo) GetPaymentType() ReturnPaymentTypeEnum {
	if o == nil {
		var ret ReturnPaymentTypeEnum
		return ret
	}

	return o.PaymentType
}

// GetPaymentTypeOk returns a tuple with the PaymentType field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetPaymentTypeOk() (*ReturnPaymentTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentType, true
}

// SetPaymentType sets field value
func (o *TradeInfo) SetPaymentType(v ReturnPaymentTypeEnum) {
	o.PaymentType = v
}

// GetHandlingCharge returns the HandlingCharge field value
func (o *TradeInfo) GetHandlingCharge() int {
	if o == nil {
		var ret int
		return ret
	}

	return o.HandlingCharge
}

// GetHandlingChargeOk returns a tuple with the HandlingCharge field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetHandlingChargeOk() (*int, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HandlingCharge, true
}

// SetHandlingCharge sets field value
func (o *TradeInfo) SetHandlingCharge(v int) {
	o.HandlingCharge = v
}

// GetPaymentTypeChargeFee returns the PaymentTypeChargeFee field value
func (o *TradeInfo) GetPaymentTypeChargeFee() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PaymentTypeChargeFee
}

// GetPaymentTypeChargeFeeOk returns a tuple with the PaymentTypeChargeFee field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetPaymentTypeChargeFeeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentTypeChargeFee, true
}

// SetPaymentTypeChargeFee sets field value
func (o *TradeInfo) SetPaymentTypeChargeFee(v float32) {
	o.PaymentTypeChargeFee = v
}

// GetTradeDate returns the TradeDate field value
func (o *TradeInfo) GetTradeDate() ECPayDateTime {
	if o == nil {
		var ret ECPayDateTime
		return ret
	}

	return o.TradeDate
}

// GetTradeDateOk returns a tuple with the TradeDate field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetTradeDateOk() (*ECPayDateTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeDate, true
}

// SetTradeDate sets field value
func (o *TradeInfo) SetTradeDate(v ECPayDateTime) {
	o.TradeDate = v
}

// GetTradeStatus returns the TradeStatus field value
func (o *TradeInfo) GetTradeStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradeStatus
}

// GetTradeStatusOk returns a tuple with the TradeStatus field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetTradeStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradeStatus, true
}

// SetTradeStatus sets field value
func (o *TradeInfo) SetTradeStatus(v string) {
	o.TradeStatus = v
}

// GetItemName returns the ItemName field value
func (o *TradeInfo) GetItemName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemName
}

// GetItemNameOk returns a tuple with the ItemName field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetItemNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemName, true
}

// SetItemName sets field value
func (o *TradeInfo) SetItemName(v string) {
	o.ItemName = v
}

// GetCustomField1 returns the CustomField1 field value
func (o *TradeInfo) GetCustomField1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomField1
}

// GetCustomField1Ok returns a tuple with the CustomField1 field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetCustomField1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomField1, true
}

// SetCustomField1 sets field value
func (o *TradeInfo) SetCustomField1(v string) {
	o.CustomField1 = v
}

// GetCustomField2 returns the CustomField2 field value
func (o *TradeInfo) GetCustomField2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomField2
}

// GetCustomField2Ok returns a tuple with the CustomField2 field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetCustomField2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomField2, true
}

// SetCustomField2 sets field value
func (o *TradeInfo) SetCustomField2(v string) {
	o.CustomField2 = v
}

// GetCustomField3 returns the CustomField3 field value
func (o *TradeInfo) GetCustomField3() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomField3
}

// GetCustomField3Ok returns a tuple with the CustomField3 field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetCustomField3Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomField3, true
}

// SetCustomField3 sets field value
func (o *TradeInfo) SetCustomField3(v string) {
	o.CustomField3 = v
}

// GetCustomField4 returns the CustomField4 field value
func (o *TradeInfo) GetCustomField4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomField4
}

// GetCustomField4Ok returns a tuple with the CustomField4 field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetCustomField4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomField4, true
}

// SetCustomField4 sets field value
func (o *TradeInfo) SetCustomField4(v string) {
	o.CustomField4 = v
}

// GetCheckMacValue returns the CheckMacValue field value
func (o *TradeInfo) GetCheckMacValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CheckMacValue
}

// GetCheckMacValueOk returns a tuple with the CheckMacValue field value
// and a boolean to check if the value has been set.
func (o *TradeInfo) GetCheckMacValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckMacValue, true
}

// SetCheckMacValue sets field value
func (o *TradeInfo) SetCheckMacValue(v string) {
	o.CheckMacValue = v
}

func (o TradeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MerchantID"] = o.MerchantID
	}
	if true {
		toSerialize["MerchantTradeNo"] = o.MerchantTradeNo
	}
	if true {
		toSerialize["StoreID"] = o.StoreID
	}
	if true {
		toSerialize["TradeNo"] = o.TradeNo
	}
	if true {
		toSerialize["TradeAmt"] = o.TradeAmt
	}
	if true {
		toSerialize["PaymentDate"] = o.PaymentDate
	}
	if true {
		toSerialize["PaymentType"] = o.PaymentType
	}
	if true {
		toSerialize["HandlingCharge"] = o.HandlingCharge
	}
	if true {
		toSerialize["PaymentTypeChargeFee"] = o.PaymentTypeChargeFee
	}
	if true {
		toSerialize["TradeDate"] = o.TradeDate
	}
	if true {
		toSerialize["TradeStatus"] = o.TradeStatus
	}
	if true {
		toSerialize["ItemName"] = o.ItemName
	}
	if true {
		toSerialize["CustomField1"] = o.CustomField1
	}
	if true {
		toSerialize["CustomField2"] = o.CustomField2
	}
	if true {
		toSerialize["CustomField3"] = o.CustomField3
	}
	if true {
		toSerialize["CustomField4"] = o.CustomField4
	}
	if true {
		toSerialize["CheckMacValue"] = o.CheckMacValue
	}
	return json.Marshal(toSerialize)
}

type NullableTradeInfo struct {
	value *TradeInfo
	isSet bool
}

func (v NullableTradeInfo) Get() *TradeInfo {
	return v.value
}

func (v *NullableTradeInfo) Set(val *TradeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTradeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTradeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTradeInfo(val *TradeInfo) *NullableTradeInfo {
	return &NullableTradeInfo{value: val, isSet: true}
}

func (v NullableTradeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTradeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
