/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

// AioCheckOutRequest struct for AioCheckOutRequest
type AioCheckOutRequest struct {
	// 特店編號(由綠界提供)
	MerchantID string `json:"MerchantID"`
	// **特店交易編號(由特店提供)** 特店交易編號均為唯一值，不可重複使用。 英數字大小寫混合 如何避免訂單編號重複請參考 FAQ 如有使用 `PlatformID` ，平台商底下所有商家之訂單編號亦不可重複。
	MerchantTradeNo string `json:"MerchantTradeNo"`
	// **特店旗下店舖代號** 提供特店填入分店代號使用，僅可用英數字大小寫混合。
	StoreID string `json:"StoreID,omitempty"`
	// **特店交易時間** 格式為 `yyyy/MM/dd HH:mm:ss`
	MerchantTradeDate ECPayDateTime `json:"MerchantTradeDate"`
	// **交易類型** 請固定填入 `aio`
	PaymentType string `json:"PaymentType"`
	// **交易金額** 請帶整數，不可有小數點。 僅限新台幣。 各付款金額的限制，請參考 <https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=3605>
	TotalAmount int32 `json:"TotalAmount"`
	// **交易描述** 傳送到綠界前，請將參數值先做 UrlEncode。
	TradeDesc string `json:"TradeDesc"`
	// **商品名稱** 1. 如果商品名稱有多筆，需在金流選擇頁一行一行顯示商品名稱的話，商品名稱請以符號#分隔。 2. 商品名稱字數限制為中英數 400 字內，超過此限制系統將自動截斷。
	ItemName string `json:"ItemName"`
	// **付款完成通知回傳網址** 當消費者付款完成後，綠界會將付款結果參數以幕後(Server POST)回傳到該網址。 詳細說明請參考付款結果通知 注意事項： 1. 請勿設定與 Client 端接收付款結果網址 OrderResultURL 相同位置，避免程式判斷錯誤。 2. 請在收到 Server 端付款結果通知後，請正確回應 1|OK 給綠界。
	ReturnURL string `json:"ReturnURL"`
	// **選擇預設付款方式** 綠界提供下列付款方式，請於建立訂單時傳送過來: - `Credit`: 信用卡及銀聯卡(需申請開通) - `WebATM`: 網路 ATM - `ATM`: 自動櫃員機 - `CVS`: 超商代碼 - `BARCODE`: 超商條碼 - `ALL`: 不指定付款方式，由綠界顯示付款方式選擇頁面。  注意事項： 1.若為手機版時不支援下列付款方式:   - WebATM:網路 ATM  2.如需要不透過綠界畫面取得 `ATM`、`CVS`、`BARCODE` 的繳費代碼，請參考 FAQ。
	ChoosePayment string `json:"ChoosePayment"`
	// **檢查碼** 請參考附錄檢查碼機制與產生檢查碼範例程式
	CheckMacValue string `json:"CheckMacValue"`
	// **Client端返回特店的按鈕連結** 消費者點選此按鈕後，會將頁面導回到此設定的網址 注意事項： 導回時不會帶付款結果到此網址，只是將頁面導回而已。 設定此參數，綠界會在付款完成或取號完成頁面上顯示[返回商店]的按鈕。 設定此參數，發生簡訊 OTP 驗證失敗時，頁面上會顯示[返回商店]的按鈕。 若未設定此參數，則綠界付款完成頁或取號完成頁面，不會顯示[返回商店]的按鈕。 若導回網址未使用 https 時，部份瀏覽器可能會出現警告訊息。
	ClientBackURL string `json:"ClientBackURL,omitempty"`
	// **商品銷售網址**
	ItemURL string `json:"ItemURL,omitempty"`
	// **備註欄位**
	Remark string `json:"Remark,omitempty"`
	// **付款子項目** 若設定此參數，建立訂單將轉導至綠界訂單成立頁，依設定的付款方式及付款子項目帶入訂單，無法選擇其他付款子項目。 請參考付款方式一覽表
	ChooseSubPayment string `json:"ChooseSubPayment,omitempty"`
	// **Client端回傳付款結果網址** 當消費者付款完成後，綠界會將付款結果參數以幕前(Client POST)回傳到該網址。 詳細說明請參考付款結果通知 注意事項： 1. 若與[ClientBackURL]同時設定，將會以此參數為主。 2. 銀聯卡及非即時交易(ATM、CVS、BARCODE)不支援此參數。
	OrderResultURL string `json:"OrderResultURL,omitempty"`
	// **是否需要額外的付款資訊** 額外的付款資訊： 若不回傳額外的付款資訊時，參數值請傳：`Ｎ`； 若要回傳額外的付款資訊時，參數值請傳：`Ｙ`，付款完成後綠界會以 Server POST 方式回傳額外付款資訊。 注意事項： 回傳額外付款資訊參數請參考-額外回傳的參數
	NeedExtraPaidInfo string `json:"NeedExtraPaidInfo,omitempty"`
	// **裝置來源** 請帶空值，由系統自動判定。
	DeviceSource string `json:"DeviceSource,omitempty"`
	// **隱藏付款** 當付款方式 `ChoosePayment` 為 `ALL` 時，可隱藏不需要的付款方式，多筆請以井號分隔(#)。 可用的參數值： - `Credit`: 信用卡 - `WebATM`: 網路 ATM - `ATM`: 自動櫃員機 - `CVS`: 超商代碼 - `BARCODE`: 超商條碼
	IgnorePayment string `json:"IgnorePayment,omitempty"`
	// **特約合作平台商代號(由綠界提供)** 為專案合作的平台商使用。 一般特店或平台商本身介接，則參數請帶放空值。 若為專案合作平台商的特店使用時，則參數請帶平台商所綁的特店編號 `MerchantID`。
	PlatformID string `json:"PlatformID,omitempty"`
	// **電子發票開立註記** 此參數為付款完成後同時開立電子發票。 若要使用時，該參數須設定為「Y」，同時還要設定「電子發票介接相關參數」 注意事項： 正式環境欲使用電子發票功能，須與綠界申請開通，若未開通請致電客服中心 `(02) 2655-1775`。
	InvoiceMark string `json:"InvoiceMark,omitempty"`
	// **自訂名稱欄位1** 提供合作廠商使用記錄用客製化使用欄位 注意事項： 特殊符號只支援 `,.#()$[];%{}:/?&@<>!`
	CustomField1 string `json:"CustomField1,omitempty"`
	// **自訂名稱欄位2** 提供合作廠商使用記錄用客製化使用欄位 注意事項： 特殊符號只支援 `,.#()$[];%{}:/?&@<>!`
	CustomField2 string `json:"CustomField2,omitempty"`
	// **自訂名稱欄位3** 提供合作廠商使用記錄用客製化使用欄位 注意事項： 特殊符號只支援 `,.#()$[];%{}:/?&@<>!`
	CustomField3 string `json:"CustomField3,omitempty"`
	// **自訂名稱欄位4** 提供合作廠商使用記錄用客製化使用欄位 注意事項： 特殊符號只支援 `,.#()$[];%{}:/?&@<>!`
	CustomField4 string `json:"CustomField4,omitempty"`
	// **CheckMacValue加密類型** 請固定填入 `1`，使用 SHA256 加密。
	EncryptType int32 `json:"EncryptType"`
	// **語系設定** 預設語系為中文，若要變更語系參數值請帶： - 英語：`ENG` - 韓語：`KOR` - 日語：`JPN` - 簡體中文：`CHI`
	Language string `json:"Language,omitempty"`
	// **超商繳費截止時間** 注意事項： `CVS`:以分鐘為單位 `BARCODE`:以天為單位 若未設定此參數，`CVS` 預設為 `10080` 分鐘(`7` 天)；BARCODE 預設為 `7` 天。 若需設定此參數，請於建立訂單時將此參數送給綠界。提醒您，CVS 帶入數值不可超過 `86400` 分鐘，超過時一律以 `86400` 分鐘計(`60` 天) 例：`08/01` 的 `20:15` 分購買商品，繳費期限為 `7` 天，表示 `8/08` 的 `20:15` 分前您必須前往超商繳費。 範例: `CVS`=`1440`(共 `1` 天)、`BARCODE`=`7`(共 `7` 天)
	StoreExpireDate int32 `json:"StoreExpireDate,omitempty"`
	// **交易描述1** 會出現在超商繳費平台螢幕上
	Desc1 string `json:"Desc_1,omitempty"`
	// **交易描述2** 會出現在超商繳費平台螢幕上
	Desc2 string `json:"Desc_2,omitempty"`
	// **交易描述3** 會出現在超商繳費平台螢幕上
	Desc3 string `json:"Desc_3,omitempty"`
	// **交易描述4** 會出現在超商繳費平台螢幕上
	Desc4 string `json:"Desc_4,omitempty"`
	// **Server 端回傳付款相關資訊** 若有設定此參數，訂單建立完成後(非付款完成)，綠界會 Server 端背景回傳消費者付款方式相關資訊(例：繳費代碼與繳費超商)。 請參考[`ATM`、`CVS` 或 `BARCODE` 的取號結果通知.] 注意事項： 頁面將會停留在綠界，顯示繳費的相關資訊。 回傳只有三段號碼，並不會回傳條碼圖，需自行轉換成 code39 的三段條碼。
	PaymentInfoURL string `json:"PaymentInfoURL,omitempty"`
	// **Client端回傳付款方式相關資訊** 若有設定此參數，訂單建立完成後(非付款完成)，綠界會從 Client 端回傳消費者付款方式相關資訊(例：繳費代碼與繳費超商)且將頁面轉到特店指定的頁面。 請參考[`ATM`、`CVS` 或 `BARCODE` 的取號結果通知.] 注意事項： 若設定此參數，將會使設定的返回特店的按鈕連結[ClientBackURL]失效。 若導回網址未使用 https 時，部份瀏覽器可能會出現警告訊息。 回傳只有三段號碼，並不會回傳條碼圖，需自行轉換成 code39 的三段條碼。
	ClientRedirectURL string `json:"ClientRedirectURL,omitempty"`
	// **記憶卡號** 使用記憶信用卡 使用：請傳 `1` 不使用：請傳 `0`
	BindingCard int32 `json:"BindingCard,omitempty"`
	// **記憶卡號識別碼** 記憶卡號識別碼 (特店代號 `MerchantID` + `廠商會員編號`)
	MerchantMemberID string `json:"MerchantMemberID,omitempty"`
}
