/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

// AioCheckOutChoosePaymentCreditOption struct for AioCheckOutChoosePaymentCreditOption
type AioCheckOutChoosePaymentCreditOption struct {
	// **記憶卡號** 使用記憶信用卡 使用：請傳 `1` 不使用：請傳 `0`
	BindingCard int32 `json:"BindingCard,omitempty"`
	// **記憶卡號識別碼** 記憶卡號識別碼 (特店代號 `MerchantID` + `廠商會員編號`)
	MerchantMemberID string `json:"MerchantMemberID,omitempty"`
}
