/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ecpayBase

import (
	"encoding/json"
)

// ExecStatusEnum **執行狀態**   回傳值如下：   1.若為 `0` 時代表已取消   2.若為 `1` 時代表執行中   3.若為 `2` 時代表執行完成
type ExecStatusEnum string

// List of ExecStatusEnum
const (
	EXECSTATUSENUM_CANCELED   ExecStatusEnum = "0"
	EXECSTATUSENUM_INPROGRESS ExecStatusEnum = "1"
	EXECSTATUSENUM_COMPLETED  ExecStatusEnum = "2"
)

// Ptr returns reference to ExecStatusEnum value
func (v ExecStatusEnum) Ptr() *ExecStatusEnum {
	return &v
}

type NullableExecStatusEnum struct {
	value *ExecStatusEnum
	isSet bool
}

func (v NullableExecStatusEnum) Get() *ExecStatusEnum {
	return v.value
}

func (v *NullableExecStatusEnum) Set(val *ExecStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableExecStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableExecStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecStatusEnum(val *ExecStatusEnum) *NullableExecStatusEnum {
	return &NullableExecStatusEnum{value: val, isSet: true}
}

func (v NullableExecStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
