/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.12
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

import (
	"encoding/json"
)

// NeedExtraPaidInfoEnum **是否需要額外的付款資訊**    額外的付款資訊：   若不回傳額外的付款資訊時，參數值請傳：`Ｎ`；   若要回傳額外的付款資訊時，參數值請傳：`Ｙ`，付款完成後綠界會以 Server POST 方式回傳額外付款資訊。     注意事項：   回傳額外付款資訊參數請參考-額外回傳的參數
type NeedExtraPaidInfoEnum string

// List of NeedExtraPaidInfoEnum
const (
	NEEDEXTRAPAIDINFOENUM_Y NeedExtraPaidInfoEnum = "Y"
	NEEDEXTRAPAIDINFOENUM_N NeedExtraPaidInfoEnum = "N"
)

// Ptr returns reference to NeedExtraPaidInfoEnum value
func (v NeedExtraPaidInfoEnum) Ptr() *NeedExtraPaidInfoEnum {
	return &v
}

type NullableNeedExtraPaidInfoEnum struct {
	value *NeedExtraPaidInfoEnum
	isSet bool
}

func (v NullableNeedExtraPaidInfoEnum) Get() *NeedExtraPaidInfoEnum {
	return v.value
}

func (v *NullableNeedExtraPaidInfoEnum) Set(val *NeedExtraPaidInfoEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableNeedExtraPaidInfoEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableNeedExtraPaidInfoEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNeedExtraPaidInfoEnum(val *NeedExtraPaidInfoEnum) *NullableNeedExtraPaidInfoEnum {
	return &NullableNeedExtraPaidInfoEnum{value: val, isSet: true}
}

func (v NullableNeedExtraPaidInfoEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNeedExtraPaidInfoEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
