/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

// EcPaySimulateEnum the model 'EcPaySimulateEnum'
type EcPaySimulateEnum int32

// List of ECPaySimulateEnum
const (
	ECPAYSIMULATEENUM_REAL_PAID EcPaySimulateEnum = 0
	ECPAYSIMULATEENUM_SIMULATED EcPaySimulateEnum = 1
)
