/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

import (
	"encoding/json"
)

// PaymentTypeEnum **特店選擇的付款方式** 請參考回覆付款方式一覽表
type PaymentTypeEnum string

// List of PaymentTypeEnum
const (
	PAYMENTTYPEENUM_WEB_ATM_TAISHIN    PaymentTypeEnum = "WebATM_TAISHIN"
	PAYMENTTYPEENUM_WEB_ATM_ESUN       PaymentTypeEnum = "WebATM_ESUN"
	PAYMENTTYPEENUM_WEB_ATM_BOT        PaymentTypeEnum = "WebATM_BOT"
	PAYMENTTYPEENUM_WEB_ATM_FUBON      PaymentTypeEnum = "WebATM_FUBON"
	PAYMENTTYPEENUM_WEB_ATM_CHINATRUST PaymentTypeEnum = "WebATM_CHINATRUST"
	PAYMENTTYPEENUM_WEB_ATM_FIRST      PaymentTypeEnum = "WebATM_FIRST"
	PAYMENTTYPEENUM_WEB_ATM_CATHAY     PaymentTypeEnum = "WebATM_CATHAY"
	PAYMENTTYPEENUM_WEB_ATM_MEGA       PaymentTypeEnum = "WebATM_MEGA"
	PAYMENTTYPEENUM_WEB_ATM_LAND       PaymentTypeEnum = "WebATM_LAND"
	PAYMENTTYPEENUM_WEB_ATM_TACHONG    PaymentTypeEnum = "WebATM_TACHONG"
	PAYMENTTYPEENUM_WEB_ATM_SINOPAC    PaymentTypeEnum = "WebATM_SINOPAC"
	PAYMENTTYPEENUM_ATM_TAISHIN        PaymentTypeEnum = "ATM_TAISHIN"
	PAYMENTTYPEENUM_ATM_ESUN           PaymentTypeEnum = "ATM_ESUN"
	PAYMENTTYPEENUM_ATM_BOT            PaymentTypeEnum = "ATM_BOT"
	PAYMENTTYPEENUM_ATM_FUBON          PaymentTypeEnum = "ATM_FUBON"
	PAYMENTTYPEENUM_ATM_CHINATRUST     PaymentTypeEnum = "ATM_CHINATRUST"
	PAYMENTTYPEENUM_ATM_FIRST          PaymentTypeEnum = "ATM_FIRST"
	PAYMENTTYPEENUM_ATM_LAND           PaymentTypeEnum = "ATM_LAND"
	PAYMENTTYPEENUM_ATM_CATHAY         PaymentTypeEnum = "ATM_CATHAY"
	PAYMENTTYPEENUM_ATM_TACHONG        PaymentTypeEnum = "ATM_TACHONG"
	PAYMENTTYPEENUM_CVS_CVS            PaymentTypeEnum = "CVS_CVS"
	PAYMENTTYPEENUM_CVS_OK             PaymentTypeEnum = "CVS_OK"
	PAYMENTTYPEENUM_CVS_FAMILY         PaymentTypeEnum = "CVS_FAMILY"
	PAYMENTTYPEENUM_CVS_HILIFE         PaymentTypeEnum = "CVS_HILIFE"
	PAYMENTTYPEENUM_CVS_IBON           PaymentTypeEnum = "CVS_IBON"
	PAYMENTTYPEENUM_BARCODE_BARCODE    PaymentTypeEnum = "BARCODE_BARCODE"
	PAYMENTTYPEENUM_CREDIT_CREDIT_CARD PaymentTypeEnum = "Credit_CreditCard"
)

// Ptr returns reference to PaymentTypeEnum value
func (v PaymentTypeEnum) Ptr() *PaymentTypeEnum {
	return &v
}

type NullablePaymentTypeEnum struct {
	value *PaymentTypeEnum
	isSet bool
}

func (v NullablePaymentTypeEnum) Get() *PaymentTypeEnum {
	return v.value
}

func (v *NullablePaymentTypeEnum) Set(val *PaymentTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentTypeEnum(val *PaymentTypeEnum) *NullablePaymentTypeEnum {
	return &NullablePaymentTypeEnum{value: val, isSet: true}
}

func (v NullablePaymentTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
