/*
 * ECPay API
 *
 * 綠界金流 API 定義文件
 *
 * API version: 0.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package base

import (
	"encoding/json"
)

// AioCheckPaymentType the model 'AioCheckPaymentType'
type AioCheckPaymentType string

// List of AioCheckPaymentType
const (
	AIOCHECKPAYMENTTYPE_AIO AioCheckPaymentType = "aio"
)

// Ptr returns reference to AioCheckPaymentType value
func (v AioCheckPaymentType) Ptr() *AioCheckPaymentType {
	return &v
}

type NullableAioCheckPaymentType struct {
	value *AioCheckPaymentType
	isSet bool
}

func (v NullableAioCheckPaymentType) Get() *AioCheckPaymentType {
	return v.value
}

func (v *NullableAioCheckPaymentType) Set(val *AioCheckPaymentType) {
	v.value = val
	v.isSet = true
}

func (v NullableAioCheckPaymentType) IsSet() bool {
	return v.isSet
}

func (v *NullableAioCheckPaymentType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAioCheckPaymentType(val *AioCheckPaymentType) *NullableAioCheckPaymentType {
	return &NullableAioCheckPaymentType{value: val, isSet: true}
}

func (v NullableAioCheckPaymentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAioCheckPaymentType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
