name: Test CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'api/**'
    - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'api/**'
    - '*.md'

jobs:

  Test:
    name: Test Go Project
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Dependency Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

